name: compile code and tests

on:
  push:
    branches: [ main, develop, issue103_CI ]
  pull_request:
    branches: [ main, develop,  issue103_CI ]

jobs:

  clang-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: clang
      run: |
        brew install clang-format
        brew uninstall clang-format
        curl https://raw.githubusercontent.com/Homebrew/homebrew-core/8fa79e8a7cb2a63efd3eaedf41a2c04a38252efe/Formula/clang-format.rb > $(find $(brew --repository) -name clang-format.rb)
        brew install clang-format
        cd core/src
        clang-format --dry-run -Werror *cpp include/*hpp
        cd -
        for component in physics
        do
          cd $component/src
          clang-format --dry-run -Werror *cpp include/*hpp
          cd -
        done
  
  
  build-and-tests-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: |
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-c++4-dev libboost-all-dev cmake
        git clone -b v2.x https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        cd ..
    - name: make
      run: |
        cmake .
        make
    - name: run tests
      run: |
        cd core/test
        for file in $(ls test*); do ./$file; done
        cd -
        for component in physics
        do
            cd $component/test
            for file in $(ls test*); do ./$file; done
            cd -
        done


  build-and-tests-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: |
        brew install netcdf
        brew install boost
        brew install cmake
        brew extract --version=2.13.9 catch2 homebrew/cask
        brew install catch2@2.13.9
    - name: make
      run: |
        cmake .
        make
    - name: run tests
      run: |
        cd core/test
        for file in $(ls test*); do ./$file; done
        cd -
        for component in physics
        do
            cd $component/test
            for file in $(ls test*); do ./$file; done
            cd -
        done
